# Generated by Django 5.0.3 on 2024-05-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='C', max_length=1),
        ),
    ]
