# Generated by Django 5.0.3 on 2024-05-06 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_request_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='driver',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.driver'),
        ),
    ]
