# Generated by Django 5.0.3 on 2024-05-08 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_slot_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='lot',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.parkinglot'),
        ),
    ]
