# Generated by Django 5.0.3 on 2024-04-25 15:38

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_parkinglot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='poly',
            field=django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326),
        ),
    ]
